name: Label PRs from feature to main

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  label_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is from feature to main
        id: check_branches
        run: echo "::set-output name=is_feature_to_main::$(if [ \"${{ github.event.pull_request.base.ref }}\" = 'main' ] && [ \"${{ github.event.pull_request.head.ref }}\" != 'main' ]; then echo true; else echo false; fi)"

      - name: Add label if PR is from feature to main
        if: steps.check_branches.outputs.is_feature_to_main == 'true'
        uses: shiftEscape/auto-label-pulls@v1.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/workflows/labeler.yml
